//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Расписание_занятий
{
    using System;
    using System.Collections.Generic;
    
    public partial class Педагоги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Педагоги()
        {
            this.Объединения = new HashSet<Объединения>();
            this.Расписание_вторник = new HashSet<Расписание_вторник>();
            this.Расписание_понедельник = new HashSet<Расписание_понедельник>();
            this.Расписание_пятница = new HashSet<Расписание_пятница>();
            this.Расписание_среда = new HashSet<Расписание_среда>();
            this.Расписание_четверг = new HashSet<Расписание_четверг>();
        }
    
        public int ID_Педагога { get; set; }
        public string ФИО { get; set; }
        public string Образование { get; set; }
        public string Должность { get; set; }
        public string Общий_стаж_работы { get; set; }
        public string Стаж_работы_по_специальности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Объединения> Объединения { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_вторник> Расписание_вторник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_понедельник> Расписание_понедельник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_пятница> Расписание_пятница { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_среда> Расписание_среда { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание_четверг> Расписание_четверг { get; set; }
    }
}
