//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Расписание_занятий
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание_понедельник
    {
        public int ID_Понедельник { get; set; }
        public Nullable<int> Номер_урока { get; set; }
        public string Время { get; set; }
        public Nullable<int> ID_Объединения { get; set; }
        public Nullable<int> ID_Педагога { get; set; }
        public Nullable<int> ID_Кабинета { get; set; }
        public Nullable<int> ID_Группы { get; set; }
        public string Комментарий_преподавателя { get; set; }
    
        public virtual Группы Группы { get; set; }
        public virtual Кабинеты Кабинеты { get; set; }
        public virtual Объединения Объединения { get; set; }
        public virtual Педагоги Педагоги { get; set; }
    }
}
